- nodeset:
    name: devstack-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- project:
    check:
      jobs:
        - devstack:
            files:
              - ^roles/
        - tempest-full-pike:
            branches: ^(?!driverfixes/).*$
            voting: false
        - tempest-full-queens:
            branches: ^(?!driverfixes/).*$
            voting: false
        - tempest-full-queens-py3:
            branches: ^(?!driverfixes/).*$
            voting: false
        - neutron-tempest-plugin-api:
            voting: false
